version: '3'

services:
# SETUP NODE SERVER-LOGIN
  server:
    container_name: server-login
    build:
        context: ./pamw-app-server-login
        dockerfile: Dockerfile
    image: matikoss/server
    ports:
      - "3000:3000"
    volumes:
      - ./pamw-app-server-login:/usr/src/app-server-login
      - /usr/src/app-server-login/node_modules
  # SETUP CLIENT
  client:
    container_name: client
    build:
        context: ./pamw-app
        dockerfile: Dockerfile
    image: matikoss/client
    ports:
      - "8000:8000"
    volumes:
      - ./pamw-app:/usr/src/app-client
      - /usr/src/app-client/node_modules
